# Generated by Django 4.2.6 on 2023-10-11 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="blog_id",
            field=models.ForeignKey(
                db_column="blog_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.blog",
            ),
        ),
    ]
