# Generated by Django 4.2.6 on 2023-10-11 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alter_comments_blog_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="author_id",
        ),
        migrations.AddField(
            model_name="comments",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
