# Generated by Django 4.2.6 on 2023-10-11 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_remove_comments_author_id_comments_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
